version: '3'

services:
  db:
    image: postgres:13
    container_name: postgres_db_node
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "2345:2345"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

  node:
    image: ${DOCKER_USERNAME:-votre_username}/nodejs_postgres:latest
    container_name: nodejs_app
    depends_on:
      - db
    ports:
      - "3050:3050"
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:2345/mydb
      - NODE_ENV=production
    restart: unless-stopped
    command: ["node", "server.js"]

volumes:
  db_data:
