version: '3'

services:
  db:
    image: postgres:13
    container_name: postgres_db_node
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "2345:2345"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    networks:
      - internal

  node:
    image: ${DOCKER_USERNAME}/nodejs_postgres:latest
    container_name: real-yoni-nodejs_app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:2345/mydb
      - NODE_ENV=production
    restart: unless-stopped
    command: ["node", "server.js"]
    networks:
      - internal
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodejs.rule=Host(`yoni.soudry-ort.online`)"
      - "traefik.http.routers.nodejs.entrypoints=web"
      - "traefik.http.services.nodejs.loadbalancer.server.port=3050"

volumes:
  db_data:

networks:
  internal:
    driver: bridge
  traefik-net:
    external: true
