services:
  db:
    image: postgres:13
    container_name: ${DOCKER_USERNAME}-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    networks:
      - internal

  node:
    image: ${DOCKER_USERNAME}/nodejs_postgres:latest
    container_name: ${DOCKER_USERNAME}-nodejs-app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/mydb
      - NODE_ENV=production
    restart: unless-stopped
    command: ["node", "server.js"]
    networks:
      - internal
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${DOCKER_USERNAME}-nodejs.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${DOCKER_USERNAME}-nodejs.entrypoints=web"
      - "traefik.http.services.${DOCKER_USERNAME}-nodejs.loadbalancer.server.port=3050"

volumes:
  db_data:

networks:
  internal:
    driver: bridge
  traefik-net:
    external: true
